version: "3.8"
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"    # Main LocalStack port
      - "4572:4572"    # S3 service port (legacy)
    environment:
      - DEBUG=1
        - USE_SSL=0
        - AWS_CBOR_DISABLE=1
        - DOCKER_HOST=unix:///var/run/docker.sock
        - HOSTNAME=localstack
        - SERVICES=s3,dynamodb
        - AWS_DEFAULT_REGION=us-east-1

    volumes:
      - "./localstack/data:/var/lib/localstack" # Persist data across container restarts
networks:
  fiap-network: