spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  application:
    name: fiap-video-extractor
  profiles:
    active: ${ENVIRONMENT:local}
  servlet:
    multipart:
      enabled: true
      max-file-size: 300MB
      max-request-size: 300MB
events:
  queues:
    extraction-info: extraction-info-queue

config:
  aws:
    access-key: ${AWS_ACCESS_KEY:localstack}
    secret-key: ${AWS_SECRET_KEY:localstack}
    address: http://127.0.0.1:4566
    region: us-east-1